-- Script SQL para configuracao do Banco de Dados Supabase (Bonetti Store)

-- 1. Criacao da tabela de produtos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Criar politica de leitura publica (permitir que qualquer visitante veja os produtos)
CREATE POLICY "Permitir leitura publica dos produtos"
ON public.products
FOR SELECT
USING (true);

-- 4. Inserir dados de exemplo (Seed)
INSERT INTO public.products (name, brand, price, image_url) VALUES
('Nike Air Max Plus Triple Black', 'Nike', 1199.90, 'https://sneakernews.com/wp-content/uploads/2025/01/nike-air-max-plus-triple-black-dm2362-002-2.jpg?w=1140'),
('Adidas Samba OG White', 'Adidas', 699.90, 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600'),
('Puma Suede Classic', 'Puma', 449.90, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600'),
('Vans Old Skool Black/White', 'Vans', 399.90, 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600');
